Feat js t2002
sganeshkumaar/Ganeshkumaar_WebTips_Assignment pull request #10
Opened 2023-09-11 07:04 UTC by sganeshkumaar

2023-09-11 20:02 UTC, lakshmipooja1510 requested changes

2023-09-12 04:01 UTC, sganeshkumaar commented on src/index.js
> +  console.log('ready to roll')
all consoles were removed

2023-09-12 04:03 UTC, sganeshkumaar commented on src/index.js
> +  console.log()
ill try to remove all consoles before raising upcoming PRs

2023-09-12 04:04 UTC, sganeshkumaar commented on src/index.js
> +  if (prefernce === 'snowflake') {
this spelling has been changed

2023-09-12 04:06 UTC, sganeshkumaar commented on src/index.js
> +function actionOnSpinnerChnage (input) {
changed this spelling

2023-09-12 10:07 UTC, sganeshkumaar commented
modified timer to run

2023-09-13 19:48 UTC, lakshmipooja1510 requested changes

2023-09-13 19:48 UTC, lakshmipooja1510 commented on src/index.js
> +  const filteredCities = cityNames.filter(filterOnPrefernece, preference)
filterOnPrefernece -> check spelling

2023-09-13 19:48 UTC, lakshmipooja1510 commented on src/index.js
> +  const preference = String(this)
check filterOnPrefernece  spelling

2023-09-14 04:01 UTC, sganeshkumaar commented on src/index.js
> +  const filteredCities = cityNames.filter(filterOnPrefernece, preference)
Spelling of the function changed

2023-09-14 11:55 UTC, lakshmipooja1510 approved these changes

2023-09-14 11:58 UTC, merged