Feat js t2003 tests
sganeshkumaar/Ganeshkumaar_WebTips_Assignment pull request #13
Opened 2023-09-27 04:43 UTC by sganeshkumaar

2023-10-01 05:21 UTC, lakshmipooja1510 requested changes

2023-10-01 05:21 UTC, lakshmipooja1510 commented on tests/unit/utils.test.js
> +  for (let i = -50; i <= 100; i++) {
need nor run for all values from - 50 to 100, instead you can run for -50, -33, 0,46, 100 something like this

2023-10-01 05:21 UTC, lakshmipooja1510 commented on tests/unit/utils.test.js
> +  expect(chooseTempCategoryOfCard(28)).toBe('snowflake')
do the same for some more temperatures like 28, 29, 30, 21, 22, 23, 17, 18, 19, 0. This will check all the limiting values. Try to follow this approach for all the tests(wherever possible)

2023-10-01 05:21 UTC, lakshmipooja1510 commented on tests/unit/utils.test.js
> +/* eslint-env jest */
You can write some tests for no of cards based on the spinner selection, the minimum and maximum cards for an icon selection

2023-10-01 06:02 UTC, sganeshkumaar commented on tests/unit/utils.test.js
> +  for (let i = -50; i <= 100; i++) {
changed to the test values

2023-10-01 14:27 UTC, sganeshkumaar commented on tests/unit/utils.test.js
> +  expect(chooseTempCategoryOfCard(28)).toBe('snowflake')
test cases added

2023-10-01 16:03 UTC, sganeshkumaar commented on tests/unit/utils.test.js
> +/* eslint-env jest */
added tests for number of cards

2023-10-02 06:25 UTC, lakshmipooja1510 approved these changes

2023-10-02 06:28 UTC, merged