Feat html t1002 completed
sganeshkumaar/Ganeshkumaar_WebTips_Assignment pull request #6
Opened 2023-08-23 05:18 UTC by sganeshkumaar

2023-08-23 10:06 UTC, lakshmipooja1510 requested changes

2023-08-23 11:17 UTC, sganeshkumaar commented on src/bottom.css
> +.bottom-section{
ok sure

2023-08-23 12:00 UTC, sganeshkumaar commented on src/middle.css
> +  display: flex;
unnecessary css has been removed

2023-08-23 12:37 UTC, sganeshkumaar commented on src/weather.html
> +            <div class="middle-section">
yeah changed to section tags

2023-08-23 12:42 UTC, sganeshkumaar commented on src/weather.html
> +                                <form action="">
removed the formtag

2023-08-24 18:57 UTC, lakshmipooja1510 requested changes

2023-08-24 18:57 UTC, lakshmipooja1510 commented on src/weather.html
> +            <section>
![image](https://github.com/sganeshkumaar/Ganeshkumaar_WebTips_Assignment/assets/91594474/05cce280-373f-4e21-b19a-de773cdf7655)
Can u remove the div and add the class name content to the section tag

2023-08-24 18:57 UTC, lakshmipooja1510 commented on src/middle.css
> +  background-color: #121212;
Do we need bg-color property as the parent already has the bg-color

2023-08-24 18:57 UTC, lakshmipooja1510 commented on src/middle.css
> +  color:white;
Can u add align-items: center for this class

2023-08-25 03:45 UTC, sganeshkumaar commented on src/weather.html
> +            <section>
changed both middle section and content class to section tag

2023-08-25 03:48 UTC, sganeshkumaar commented on src/middle.css
> +  background-color: #121212;
Yes we need it , if background color for preference-select class is not given ,when it sticks ,its background would be transparent. so that's why i added background color
![Screenshot (17)](https://github.com/sganeshkumaar/Ganeshkumaar_WebTips_Assignment/assets/141948184/47a541a4-20ff-4112-9077-caa975766d41)

2023-08-25 04:15 UTC, sganeshkumaar commented on src/middle.css
> +  color:white;
yeah i have aligned the image and text to center now.

2023-08-25 09:43 UTC, merged