Feat html t1003
sganeshkumaar/Ganeshkumaar_WebTips_Assignment pull request #7
Opened 2023-08-28 07:13 UTC by sganeshkumaar

2023-08-29 07:04 UTC, lakshmipooja1510 requested changes

2023-08-29 09:06 UTC, sganeshkumaar commented on src/bottom.css
> +    align-items: flex-end;
align flex-end property removed

2023-08-29 09:06 UTC, sganeshkumaar commented on src/bottom.css
> +    height:fit-content;
removed the height property

2023-08-29 09:07 UTC, sganeshkumaar commented on src/bottom.css
> +    margin: auto;
i used margin for centering the div but now ive changed it to flex properties

2023-08-29 09:51 UTC, sganeshkumaar commented on src/bottom.css
> +    height: 95%;
value changed to px

2023-08-29 09:54 UTC, sganeshkumaar commented on src/bottom.css
> +    width: fit-content;
width removed in tile-city-details and tile-factors

2023-08-29 09:55 UTC, sganeshkumaar commented on src/bottom.css
> +
empty lines removed in bottom.css

2023-08-29 09:56 UTC, sganeshkumaar commented on src/bottom.css
> +    color: #FFF;
text color property removed

2023-08-29 09:57 UTC, sganeshkumaar commented on src/bottom.css
> +    width: auto;
width property removed

2023-08-29 09:57 UTC, sganeshkumaar commented on src/weather.html
> +
empty line removed

2023-08-29 16:34 UTC, lakshmipooja1510 requested changes

2023-08-29 16:34 UTC, lakshmipooja1510 commented on src/bottom.css
> +    display:flex;
do we need flex and flex-direction

2023-08-29 16:34 UTC, lakshmipooja1510 commented on src/bottom.css
> +    align-self: center;
Do we need align-self and width property

2023-08-29 17:12 UTC, sganeshkumaar commented on src/bottom.css
> +    display:flex;
i gave the bottom section as flex to center the bottom head

2023-08-29 17:13 UTC, sganeshkumaar commented on src/bottom.css
> +    align-self: center;
this centers, only the bottom head on center
![image](https://github.com/sganeshkumaar/Ganeshkumaar_WebTips_Assignment/assets/141948184/2ee9983a-0461-43fb-a272-70d2e11922b0)

2023-08-30 04:03 UTC, sganeshkumaar commented on src/bottom.css
> +    align-self: center;
yes we also need width property to make the head text and icons go apart

2023-08-30 13:10 UTC, lakshmipooja1510 approved these changes

2023-08-30 14:25 UTC, merged